### PR TITLE
Automatically fill in fwupdate.efidir with /etc/os-release

### PR DESCRIPTION
**Pull request by superm1**

### CODE REVIEW

**Comment by hughsie** [comment]
Is this going to work on Fedora Atomic? I think you have to use `/usr/lib/os-release` there.

**Comment by superm1** [comment]
I think in Fedora atomic you may want to manually set it in build config, but let me restore the error in that scenario then.

**Comment by superm1** [comment]
@hughsie can you take another look?  I think this should cover any distros that do it either way now.

**Comment by hughsie** [comment]
I think that's much better. +1 from me, but I think Peter ought to approve this too.

**Pull request merged**
